### ISSUE TITLE
Failed to share page on network: Syntax error - Unexpected URL token

### ISSUE THREAD

**Issue by sammcj** [samepage-network/obsidian-samepage#2]
Testing out SamePage for the first time - trying to get it to work on some web-clipped notes and getting "Syntax error" ... "Unexpected URL token".

I think there's a few issues here though:

1. The error / problem itself
2. The error message
	- Is crammed into a very tall, long output that's not easily readable
	- Disappears after a few seconds
	- Is not meaningful / helpful for the end user
3. Clicking the SamePage icon for more information
	- Shows a popup that is cut off / not all visible
	- Doesn't show any errors

## Screenshots

Error:

<img width="375" alt="SCR-20221228-bel" src="https://user-images.githubusercontent.com/862951/209722937-a447acb5-cb86-4885-a081-86965eaa5b1f.png">

Clicking the SamePage icon:

<img width="276" alt="SCR-20221228-bj2" src="https://user-images.githubusercontent.com/862951/209723269-2a73efc2-9914-4cde-a183-3bb58ff197cc.png">

<img width="352" alt="SCR-20221228-bj7" src="https://user-images.githubusercontent.com/862951/209723276-0a8e0263-6302-4791-bad9-a0b5d2ce8754.png">

## Other information

- Plugin: 2.3.13
- Obsidian: 1.1.9
- Platform: macOS 13.1

---

## Note source

```markdown
# How Mental Time Travel Can Make Us Better People
In late summer 1978, tensions broiled between then Egyptian President Anwar el-Sadat and Israeli Prime Minister Menachem Begin. For nearly two weeks, United States President Jimmy Carter and scores of advisors struggled to help the leaders reach an agreement that would end decades of fighting between the two countries. The high-stakes meeting at Camp David seemed to have crumpled under the weight of the conflict as Begin reportedly called off negotiations and asked President Carter to call him a car.

While Begin was packing up to go—and leave behind the possibility of regional detente—President Carter brought in eight copies of a photograph of the three leaders together. On each he had written the name of one of Begin’s grandchildren and a note about his own hope for peace in the future.

Upon looking over these inscriptions, Begin’s countenance changed. He “put his bags down, and he said, ‘Mr. President, I’ll make one last try,’” [recalled](https://carterschool.gmu.edu/why-study-here/legacy-leadership/camp-david-hal-saunders-and-responsibility-peacemaking) former Domestic Affairs Advisor Stuart Eizenstat in 2018. Begin then acquiesced on a central point of contention, and the Camp David Accord was reached, resulting in a formal treaty that has held ever since.

> _Mental time travel might help us to circumvent impulsive choices or opportunistic motivation._

What changed in Begin’s mind in that instant? According to researchers Olga Maria Klimecki-Lenz, Patricia Cernadas Curotto, and their colleagues, it was an opportunity for Begin to think about the future—if even for just a fleeting moment—that shifted his approach, like a change in weather, to orient toward cooperation. At least that was their working hypothesis.

Plenty of research has shown that thinking about the future [can shift](https://www.sciencedirect.com/science/article/abs/pii/S1053810016302252) our _intentions_ to behave better, from planning to [save more money for retirement](https://hbr.org/2013/06/you-make-better-decisions-if-you-see-your-senior-self) to [helping out](https://pubmed.ncbi.nlm.nih.gov/29178984/) in a theoretical situation.

But do these intentions translate to a change in our _behavior_? This is what Klimecki-Lenz, who is a neuroscientist and psychologist, as well as a practicing mediator who has worked with diplomats and heads of state, and Cernadas Curotto, a psychology researcher at the University of Geneva in Switzerland, and their colleagues set out to answer through [a study published earlier this year](https://journals.plos.org/plosone/article?id

Source: https://nautil.us/how-mental-time-travel-can-make-us-better-people-254241/
```

Hope this bug report helps!

**Comment by dvargasfuertes** [comment]
Thanks for the error report! Fix is coming out soon.

1. The problem seemed to be the unclosed alias causing a parsing issue
2. This is an error message that was supposed to be emailed to us instead of shown to the end user - Fixing the issue in this spot now
3. The samepage popup is meant to display app notifications, so it's not intended to hold system errors (as mentioned in 2, those should be sent to us). It being cut off though is unexpected, can you share a screen shot of the full workspace?
