### ISSUE TITLE
Obsidian hanged when sharing a page

### ISSUE THREAD

**Issue by cristianvasquez** [samepage-network/obsidian-samepage#3]
Hi, 

I'm testing the plugin, but I had trouble sharing some pages.

With simple text, it seems there is no problem; however, some of them hang obsidian, and I have to kill the process.
[Test.md](https://github.com/samepage-network/obsidian-samepage/files/10609344/Test.md)

I'm attaching a note that hangs samepage

**Comment by dvargasfuertes** [comment]
Sorry for the issues and thanks for sharing! We're currently looking to secure funding, but once we do, I'd consider this a p0 bug that we'll prioritize. 

From my initial investigation, it appears the parser is considering far too many possibilities (~1.5M states) as opposed to being an infinite loop. There are probably obvious optimizations here that we're missing to prune 99.99% percent of those
