### ISSUE TITLE
Missing Tailwind CSS

### ISSUE THREAD

**Issue by mdroidian** [samepage-network/obsidian-samepage#6]
![image](https://user-images.githubusercontent.com/3792666/236581667-129ff3c8-7eda-40df-bf66-bebb9d293942.png)

![image](https://user-images.githubusercontent.com/3792666/236581724-9742d77f-f91e-4668-9f6e-889ed4316100.png)

**Comment by dvargasfuertes** [comment]
I realize for Obsidian, this `mirror` param will be broken for other developers: https://github.com/samepage-network/obsidian-samepage/blob/main/scripts/args.js#L4

How did you get it loading locally? I think I'm going to change it to an environment variable `OBSIDIAN_PLUGIN_PATH` and allow developers to configure their own locally

**Comment by dvargasfuertes** [comment]
This should also now be fixed on 2.7.0

**Comment by mdroidian** [comment]
> How did you get it loading locally?

I just copied and pasted the `dist` files into a plugin folder.

**Comment by dvargasfuertes** [comment]
Ok cool that's basically all that `mirror` does. on the latest pull now, if you add `OBSIDIAN_PLUGIN_PATH` to your `.env` file, then it will mirror automatically instead of needing to do so manually
