### ISSUE TITLE
A few plugin issues

### ISSUE THREAD

**Issue by mdroidian** [samepage-network/obsidian-samepage#8]
- [x] onload connect / disconnect
- [x] notification icon CSS issue
- [x] page menu not showing up

https://github.com/samepage-network/obsidian-samepage/assets/3792666/6bb8829b-ed2a-49dd-9a97-3284ad2b3243

**Comment by dvargasfuertes** [comment]
the first one is solved with a simple `npm install samepage@latest` - I noticed that bug too and have incorporated the fix to the main library, just havent upgraded the lib yet.

The second one should be straightforward - ideally it is in the location that you mentioned.

third one could get hairy - our observer logic is a bit tough to grok but should feel familiar with other RoamJS work.

Wanna take a swing at this?

**Comment by mdroidian** [comment]
Absolutely!

**Comment by mdroidian** [comment]
Upon further inspection, I think I've narrowed down the "page menu not showing up" to 

1. Navigate to shared page (`shared-page.md`)
2. Navigate to a not shared page (`any-not-shared-page.md`)
3. Navigate back to previous shared page (`shared-page.md`)

Then `sel` is from `shared-page.md` so script `return`s
https://github.com/samepage-network/obsidian-samepage/blob/7e727c5cb1c275d871134292ac9682524dba0475/src/protocols/sharePageWithNotebook.ts#L126-L129

What is the purpose of `if (existingNotebookPageId === notebookPageId) return;`? @dvargas92495

**Comment by dvargasfuertes** [comment]
this is to prevent multiple elements from rendering - looks like on unmount, we should remove the `data-samepage-shared` attribute
